server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # --- 1. REDIRECTION DE L'API VERS TON BACKEND LOCAL ---
    location /projects {
        # 1. Nginx réécrit /projects en /api/projects silencieusement
        rewrite ^/projects(.*)$ /api/projects$1 break;
        
        # 2. Il envoie la requête modifiée à ton backend
        proxy_pass https://portfolio-backend-1-i55r.onrender.com/;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # --- 2. COMPRESSION GZIP ---
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # --- 3. MISE EN CACHE DES FICHIERS STATIQUES ---
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|webp)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }

    # --- 4. ROUTAGE REACT ---
    location / {
        try_files $uri $uri/ /index.html;
    }
}